/**
 * Core data models for API Endpoint Testing Transformation
 * Feature: api-endpoint-testing-transformation
 */

import {
  HttpMethod,
  AuthType,
  TestFramework,
  Environment,
  TestStatus,
  ScmProvider,
  DatabaseType,
} from './enums.js';

// Re-export enums for convenience
export { HttpMethod, AuthType, TestFramework, Environment, TestStatus, ScmProvider, DatabaseType };

/**
 * Represents a Jira task with all relevant information
 */
export interface JiraTask {
  key: string; // e.g., "PROJ-123"
  summary: string;
  description: string;
  assignee: string;
  status: string;
  projectKey: string;
  customFields: Record<string, unknown>;
  labels: string[];
  createdAt: Date;
  updatedAt: Date;
}

/**
 * Specification for an API endpoint to be tested
 */
export interface EndpointSpec {
  url: string; // Full URL or path
  method: HttpMethod;
  headers: Record<string, string>;
  requestBody?: Record<string, unknown>;
  expectedStatus: number; // e.g., 200, 201
  expectedResponseSchema?: Record<string, unknown>;
  authType?: AuthType;
  testScenarios: string[]; // e.g., ["success", "unauthorized", "not_found"]
  performanceThresholdMs?: number;
}

/**
 * Information about a repository to retrieve context from
 */
export interface RepositoryInfo {
  url: string; // e.g., "https://github.com/org/repo"
  provider: ScmProvider;
  branch: string; // default: "main"
  authToken: string; // from environment
  cloneDepth: number; // shallow clone depth
}

/**
 * Result of task analysis prior to endpoint parsing
 */
export interface TaskAnalysisResult {
  isValid: boolean;
  requiresEndpointParsing: boolean;
  repository?: RepositoryInfo;
  normalizedDescription: string;
  errors: string[];
  warnings: string[];
}

/**
 * Content of a file retrieved from repository
 */
export interface FileContent {
  path: string;
  content: string;
  size: number;
}

/**
 * Context information for test generation
 */
export interface TestContext {
  apiSpecifications: FileContent[];
  existingTests: FileContent[];
  documentation: FileContent[];
  configurationFiles: FileContent[];
  detectedFramework?: TestFramework;
  detectedDatabases?: DatabaseType[];
  repositoryInfo: RepositoryInfo;
}

/**
 * A single test file generated by AI
 */
export interface TestFile {
  path: string; // e.g., "tests/api/test_users.py"
  content: string;
  testCount: number;
  coveredEndpoints: string[];
}

/**
 * Collection of generated test files and metadata
 */
export interface GeneratedTests {
  testFiles: TestFile[];
  framework: TestFramework;
  requiredEnvVars: string[];
  setupCommands: string[];
  runCommand: string;
  warnings: string[];
}

/**
 * Performance metrics for API tests
 */
export interface PerformanceMetrics {
  minResponseTimeMs: number;
  maxResponseTimeMs: number;
  avgResponseTimeMs: number;
  successRate: number;
  requestsPerSecond?: number;
}

/**
 * Result of a single test case
 */
export interface TestCase {
  name: string;
  endpoint: string;
  status: TestStatus;
  durationMs: number;
  errorMessage?: string;
  requestDetails?: Record<string, unknown>;
  responseDetails?: Record<string, unknown>;
}

/**
 * Complete test execution results
 */
export interface TestResults {
  totalTests: number;
  passedTests: number;
  failedTests: number;
  skippedTests: number;
  durationSeconds: number;
  testCases: TestCase[];
  performanceMetrics?: PerformanceMetrics;
  timestamp: Date;
}

/**
 * Configuration for test execution
 */
export interface ExecutionConfig {
  environment: Environment;
  timeoutSeconds: number; // default: 300
  retryCount: number; // default: 3
  retryBackoffSeconds: number[]; // [1, 2, 4]
  allowDestructiveOps: boolean; // false for production
  credentials: Record<string, string>; // environment variables
}

/**
 * Configuration for SCM commits
 */
export interface CommitConfig {
  commitTestScripts: boolean; // default: true
  commitTestResults: boolean; // default: false
  createPullRequest: boolean; // default: false
  branchPrefix: string; // default: "api-test"
}

/**
 * Result of a validation operation
 */
export interface ValidationResult {
  valid: boolean;
  errors: string[];
  warnings: string[];
}

/**
 * Webhook configuration for Jira
 */
export interface WebhookConfig {
  url: string;
  secret: string;
  events: string[];
}

/**
 * Result of a commit operation
 */
export interface CommitResult {
  success: boolean;
  commitSha?: string;
  branchName: string;
  pullRequestUrl?: string;
  error?: string;
}

/**
 * Result of a command execution
 */
export interface ExecutionResult {
  exitCode: number;
  stdout: string;
  stderr: string;
  timedOut: boolean;
  durationMs: number;
}

/**
 * Docker container reference
 */
export interface Container {
  id: string;
  name: string;
  image: string;
  status: string;
}

/**
 * Structured prompt for AI test generation
 */
export interface StructuredPrompt {
  task: string;
  framework: TestFramework;
  endpoints: EndpointSpec[];
  context: {
    existingTests?: string;
    apiSpec?: string;
    documentation?: string;
  };
  environment: Environment;
  constraints: {
    allowedTestPaths: string[];
    forbiddenOperations: string[];
    requiredValidations: string[];
    globalCoverageRequirements?: string[];
  };
  testRules: {
    includeSuccessCases: boolean;
    includeErrorCases: boolean;
    includeAuthTests: boolean;
    includeValidationTests: boolean;
  };
}

/**
 * Structured response from AI test generation
 */
export interface StructuredResponse {
  summary: string;
  testFiles: TestFile[];
  executionHints: {
    requiredEnvVars: string[];
    setupCommands: string[];
    runCommand: string;
  };
  warnings: string[];
}
